import { writeFileSync } from 'node:fs'
import { buildFormAttachment } from '../api/_lib/form-attachment.js'

const sample = {
  id: 'preview',
  sessionId: 'preview',
  recalculationNumber: 0,
  businessName: 'Acme Plumbing Co.',
  industry: 'plumbing',
  city: 'Austin',
  state: 'TX',
  yearsInBusiness: 12,
  employees: 18,
  inputMode: 'know',
  revenue: '2400000',
  ebitda: '480000',
  earnings: null,
  interestExpense: null,
  taxesPaid: null,
  depreciationAmort: null,
  ownerSalary: '160000',
  marketSalary: '95000',
  addbacks: '35000',
  adjEbitda: '420000',
  baseMultiple: null,
  estimatedMultiple: '4.2',
  yearsBonus: null,
  revenueScaleBonus: null,
  valuationLow: '1500000',
  valuationBase: '1764000',
  valuationHigh: '2100000',
  valueScore: 62,
  scoreBand: 'Good',
  trajectoryUpliftAmount: null,
  trajectoryNewValuationLow: null,
  trajectoryNewValuationBase: null,
  trajectoryNewValuationHigh: null,
  trajectoryTopFactors: null,
  goodFactors: null,
  badFactors: null,
  vipRecommendations: null,
  growthSlider: 4,
  ownerDepSlider: 2,
  recurringSlider: 3,
  custConcSlider: 3,
  systemsSlider: 4,
  finRecordsSlider: 5,
  leadEmail: 'owner@acmeplumbing.com',
  quizTimeline: '12-24 months',
  quizAdvisorySource: 'Referral',
  calculatedAt: new Date(),
  reportSentAt: null,
  createdAt: new Date(),
  updatedAt: new Date(),
} as const

const { content, filename } = await buildFormAttachment(sample as any)
writeFileSync(`/tmp/${filename}`, content)
console.log(`✓ Saved to /tmp/${filename}`)
